import { defineType, defineField, defineArrayMember } from 'sanity'
import { CogIcon } from '@sanity/icons'

export const siteSettings = defineType({
  name: 'siteSettings',
  title: 'Site Settings',
  type: 'document',
  icon: CogIcon,
  groups: [
    { name: 'general', title: 'General', default: true },
    { name: 'seo', title: 'SEO & Metadata' },
    { name: 'social', title: 'Social & Links' },
    { name: 'contact', title: 'Contact & Hours' },
    { name: 'announcement', title: 'Announcements' },
    { name: 'analytics', title: 'Analytics & Scripts' },
    { name: 'compliance', title: 'Compliance & Legal' },
    { name: 'appearance', title: 'Appearance' },
    { name: 'advanced', title: 'Advanced' },
  ],
  fields: [
    // ── General ──────────────────────────────────────────────
    defineField({
      name: 'siteName',
      title: 'Site Name',
      type: 'string',
      group: 'general',
      description: 'Used in title tags, schema.org, and as the brand name across the site',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'siteTagline',
      title: 'Tagline',
      type: 'string',
      group: 'general',
    }),
    defineField({
      name: 'siteDescription',
      title: 'Site Description',
      type: 'text',
      rows: 3,
      group: 'general',
      description: 'Default meta description fallback used when a page has none',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'siteUrl',
      title: 'Site URL',
      type: 'url',
      group: 'general',
      description: 'Canonical base URL, e.g. https://www.firstcreditunion.co.nz',
      validation: (rule) =>
        rule.required().uri({ scheme: ['https'] }).error('Must be a valid HTTPS URL'),
    }),
    defineField({
      name: 'logo',
      title: 'Logo',
      type: 'image',
      group: 'general',
      description: 'Primary logo (SVG or PNG with transparency). Used in header, OG fallback, and schema.org.',
      options: { hotspot: true },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'logoAlt',
      title: 'Logo Alt Text',
      type: 'string',
      group: 'general',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'logoDark',
      title: 'Logo (Dark Mode)',
      type: 'image',
      group: 'general',
      description: 'Optional dark-mode variant of the logo',
      options: { hotspot: true },
    }),
    defineField({
      name: 'favicon',
      title: 'Favicon',
      type: 'file',
      group: 'general',
      description: 'Accepts .ico, .png, or .svg. 32×32 recommended. Falls back to the logo if not set.',
      options: {
        accept: '.ico,.png,.svg,image/x-icon,image/png,image/svg+xml',
      },
    }),
    defineField({
      name: 'appleTouchIcon',
      title: 'Apple Touch Icon',
      type: 'image',
      group: 'general',
      description: '180×180 icon for iOS devices',
    }),
    defineField({
      name: 'locale',
      title: 'Default Locale',
      type: 'string',
      group: 'general',
      initialValue: 'en-NZ',
      options: {
        list: [
          { title: 'English (NZ)', value: 'en-NZ' },
          { title: 'Te Reo Māori', value: 'mi-NZ' },
        ],
      },
    }),
    defineField({
      name: 'currency',
      title: 'Currency',
      type: 'string',
      group: 'general',
      initialValue: 'NZD',
      readOnly: true,
    }),
    defineField({
      name: 'dateFormat',
      title: 'Date Format',
      type: 'string',
      group: 'general',
      initialValue: 'DD/MM/YYYY',
      options: {
        list: ['DD/MM/YYYY', 'MM/DD/YYYY', 'YYYY-MM-DD'],
      },
    }),
    defineField({
      name: 'timezone',
      title: 'Timezone',
      type: 'string',
      group: 'general',
      initialValue: 'Pacific/Auckland',
      readOnly: true,
    }),

    // ── SEO & Metadata ───────────────────────────────────────
    defineField({
      name: 'defaultSeoTitle',
      title: 'Default SEO Title',
      type: 'string',
      group: 'seo',
      description: 'Fallback title when a page has none',
    }),
    defineField({
      name: 'titleTemplate',
      title: 'Title Template',
      type: 'string',
      group: 'seo',
      description: 'Pattern for page titles. Use %s for the page title, e.g. "%s | First Credit Union"',
      initialValue: '%s | First Credit Union',
    }),
    defineField({
      name: 'defaultSeoDescription',
      title: 'Default Meta Description',
      type: 'text',
      rows: 3,
      group: 'seo',
      description: 'Fallback meta description when a page has none',
    }),
    defineField({
      name: 'defaultOgImage',
      title: 'Default Social Share Image',
      type: 'image',
      group: 'seo',
      description: 'Default Open Graph image (1200×630) used when pages have no OG image',
      options: { hotspot: true },
    }),
    defineField({
      name: 'twitterHandle',
      title: 'Twitter / X Handle',
      type: 'string',
      group: 'seo',
      description: 'e.g. @FirstCreditUnion — used for twitter:site meta tag',
    }),
    defineField({
      name: 'twitterCardType',
      title: 'Twitter Card Type',
      type: 'string',
      group: 'seo',
      initialValue: 'summary_large_image',
      options: {
        list: [
          { title: 'Summary', value: 'summary' },
          { title: 'Summary with Large Image', value: 'summary_large_image' },
        ],
        layout: 'radio',
      },
    }),
    defineField({
      name: 'googleSiteVerification',
      title: 'Google Site Verification',
      type: 'string',
      group: 'seo',
      description: 'Google Search Console verification code',
    }),
    defineField({
      name: 'bingSiteVerification',
      title: 'Bing Site Verification',
      type: 'string',
      group: 'seo',
      description: 'Bing Webmaster Tools verification code',
    }),
    defineField({
      name: 'noIndexSite',
      title: 'Disable Search Engine Indexing',
      type: 'boolean',
      group: 'seo',
      description: 'Emergency kill-switch: adds noindex to the entire site. Use during development or emergencies.',
      initialValue: false,
    }),
    defineField({
      name: 'robotsTxtOverride',
      title: 'Robots.txt Override',
      type: 'text',
      group: 'seo',
      description: 'Custom robots.txt content. Leave blank for auto-generated default.',
    }),
    defineField({
      name: 'enableJsonLd',
      title: 'Enable Organization JSON-LD',
      type: 'boolean',
      group: 'seo',
      description: 'Output CreditUnion schema.org structured data on every page',
      initialValue: true,
    }),

    // ── Social & Links ───────────────────────────────────────
    defineField({
      name: 'socialLinks',
      title: 'Social Media Profiles',
      type: 'array',
      group: 'social',
      of: [defineArrayMember({ type: 'socialLink' })],
    }),

    // ── Contact & Hours ──────────────────────────────────────
    defineField({
      name: 'primaryPhone',
      title: 'Primary Phone',
      type: 'string',
      group: 'contact',
      description: 'Main contact number. Include country code, e.g. +64 7 834 2845',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'tollFreePhone',
      title: 'Toll-Free / 0800 Number',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'primaryEmail',
      title: 'Primary Email',
      type: 'string',
      group: 'contact',
      validation: (rule) => rule.required().email(),
    }),
    defineField({
      name: 'headOfficeAddress',
      title: 'Head Office Address',
      type: 'address',
      group: 'contact',
    }),
    defineField({
      name: 'postalAddress',
      title: 'Postal Address',
      type: 'address',
      group: 'contact',
      description: 'PO Box or postal address if different from head office',
    }),
    defineField({
      name: 'businessHours',
      title: 'Business Hours',
      type: 'array',
      group: 'contact',
      of: [defineArrayMember({ type: 'dayHours' })],
    }),
    defineField({
      name: 'holidayNotice',
      title: 'Holiday Notice',
      type: 'text',
      rows: 2,
      group: 'contact',
      description: 'Short notice about public holiday hours',
    }),

    // ── Announcements ────────────────────────────────────────
    defineField({
      name: 'announcementBar',
      title: 'Announcement Bar',
      type: 'announcementBar',
      group: 'announcement',
      description: 'Site-wide banner for alerts, promotions, or maintenance notices',
    }),

    // ── Analytics & Scripts ──────────────────────────────────
    defineField({
      name: 'enableAnalytics',
      title: 'Enable Analytics',
      type: 'boolean',
      group: 'analytics',
      description: 'Master toggle to enable/disable all analytics tracking',
      initialValue: true,
    }),
    defineField({
      name: 'googleAnalyticsId',
      title: 'Google Analytics 4 ID',
      type: 'string',
      group: 'analytics',
      description: 'GA4 measurement ID, e.g. G-XXXXXXXXXX',
    }),
    defineField({
      name: 'googleTagManagerId',
      title: 'Google Tag Manager ID',
      type: 'string',
      group: 'analytics',
      description: 'GTM container ID, e.g. GTM-XXXXXXX',
    }),
    defineField({
      name: 'hotjarId',
      title: 'Hotjar Site ID',
      type: 'string',
      group: 'analytics',
    }),
    defineField({
      name: 'metaPixelId',
      title: 'Meta Pixel ID',
      type: 'string',
      group: 'analytics',
      description: 'Facebook / Meta Pixel ID',
    }),
    defineField({
      name: 'linkedinPartnerId',
      title: 'LinkedIn Insight Tag Partner ID',
      type: 'string',
      group: 'analytics',
    }),
    defineField({
      name: 'customHeadScripts',
      title: 'Custom Head Scripts',
      type: 'text',
      group: 'analytics',
      description:
        '⚠️ SECURITY WARNING: Raw script tags injected into <head>. Only add trusted scripts — malicious code can compromise user data.',
    }),
    defineField({
      name: 'customBodyScripts',
      title: 'Custom Body Scripts',
      type: 'text',
      group: 'analytics',
      description:
        '⚠️ SECURITY WARNING: Raw script tags injected before </body>. Only add trusted scripts — malicious code can compromise user data.',
    }),

    // ── Compliance & Legal ───────────────────────────────────
    defineField({
      name: 'registeredName',
      title: 'Registered Entity Name',
      type: 'string',
      group: 'compliance',
      description: 'Legal registered name of the organisation',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'nzbn',
      title: 'NZBN',
      type: 'string',
      group: 'compliance',
      description: 'New Zealand Business Number',
    }),
    defineField({
      name: 'fspNumber',
      title: 'FSP Number',
      type: 'string',
      group: 'compliance',
      description: 'Financial Service Provider registration number',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'disputeResolutionScheme',
      title: 'Dispute Resolution Scheme',
      type: 'disputeResolutionScheme',
      group: 'compliance',
    }),
    defineField({
      name: 'regulatoryBody',
      title: 'Regulatory Body Statement',
      type: 'string',
      group: 'compliance',
      description: 'e.g. "Regulated by the Financial Markets Authority (FMA)"',
    }),
    defineField({
      name: 'copyrightNotice',
      title: 'Copyright Notice',
      type: 'string',
      group: 'compliance',
      description: 'Footer copyright text. Use {year} for auto-replacement with the current year.',
      initialValue: 'Copyright {year} First Credit Union. All rights reserved.',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'privacyPolicyUrl',
      title: 'Privacy Policy URL',
      type: 'string',
      group: 'compliance',
      description: 'URL path to the privacy policy page, e.g. /privacy-policy',
    }),
    defineField({
      name: 'termsUrl',
      title: 'Terms & Conditions URL',
      type: 'string',
      group: 'compliance',
    }),
    defineField({
      name: 'disclosureStatementUrl',
      title: 'Disclosure Statement URL',
      type: 'string',
      group: 'compliance',
      description: 'CCCFA requirement — link to disclosure statement',
    }),
    defineField({
      name: 'complaintsUrl',
      title: 'Complaints Process URL',
      type: 'string',
      group: 'compliance',
    }),
    defineField({
      name: 'accessibilityStatementUrl',
      title: 'Accessibility Statement URL',
      type: 'string',
      group: 'compliance',
    }),
    defineField({
      name: 'cookieConsentEnabled',
      title: 'Enable Cookie Consent Banner',
      type: 'boolean',
      group: 'compliance',
      initialValue: true,
    }),
    defineField({
      name: 'cookieConsentMessage',
      title: 'Cookie Consent Message',
      type: 'text',
      rows: 2,
      group: 'compliance',
      description: 'Custom cookie consent banner text',
    }),

    // ── Appearance ───────────────────────────────────────────
    defineField({
      name: 'enableDarkMode',
      title: 'Enable Dark Mode Toggle',
      type: 'boolean',
      group: 'appearance',
      initialValue: false,
    }),
    defineField({
      name: 'headerStyle',
      title: 'Header Style',
      type: 'string',
      group: 'appearance',
      initialValue: 'sticky',
      options: {
        list: [
          { title: 'Transparent', value: 'transparent' },
          { title: 'Solid', value: 'solid' },
          { title: 'Sticky', value: 'sticky' },
        ],
        layout: 'radio',
      },
    }),
    defineField({
      name: 'footerStyle',
      title: 'Footer Style',
      type: 'string',
      group: 'appearance',
      initialValue: 'standard',
      options: {
        list: [
          { title: 'Standard', value: 'standard' },
          { title: 'Minimal', value: 'minimal' },
          { title: 'Expanded', value: 'expanded' },
        ],
        layout: 'radio',
      },
    }),
    defineField({
      name: 'customCss',
      title: 'Custom CSS',
      type: 'text',
      group: 'appearance',
      description: '⚠️ Use with caution — custom CSS injected globally. May break site styling.',
    }),
    defineField({
      name: 'fontPrimary',
      title: 'Primary Font Override',
      type: 'string',
      group: 'appearance',
      description: 'Font family name override. Leave blank to use the default (Poppins).',
    }),
    defineField({
      name: 'fontSecondary',
      title: 'Secondary Font Override',
      type: 'string',
      group: 'appearance',
    }),

    // ── Advanced ─────────────────────────────────────────────
    defineField({
      name: 'maintenanceMode',
      title: 'Maintenance Mode',
      type: 'boolean',
      group: 'advanced',
      description: 'When enabled, shows a maintenance page to all visitors',
      initialValue: false,
    }),
    defineField({
      name: 'maintenanceMessage',
      title: 'Maintenance Message',
      type: 'text',
      rows: 3,
      group: 'advanced',
    }),
    defineField({
      name: 'maintenanceAllowedIPs',
      title: 'Allowed IPs (Bypass Maintenance)',
      type: 'array',
      group: 'advanced',
      of: [defineArrayMember({ type: 'string' })],
      description: 'IP addresses that can bypass maintenance mode',
    }),
    defineField({
      name: 'custom404Title',
      title: 'Custom 404 Title',
      type: 'string',
      group: 'advanced',
      description: 'Fallback: "Page Not Found"',
    }),
    defineField({
      name: 'custom404Description',
      title: 'Custom 404 Description',
      type: 'text',
      rows: 2,
      group: 'advanced',
    }),
    defineField({
      name: 'custom500Title',
      title: 'Custom 500 Title',
      type: 'string',
      group: 'advanced',
      description: 'Fallback: "Something Went Wrong"',
    }),
    defineField({
      name: 'custom500Description',
      title: 'Custom 500 Description',
      type: 'text',
      rows: 2,
      group: 'advanced',
    }),
    defineField({
      name: 'enablePwa',
      title: 'Enable PWA',
      type: 'boolean',
      group: 'advanced',
      description: 'Enable Progressive Web App features',
      initialValue: false,
    }),
    defineField({
      name: 'pwaShortName',
      title: 'PWA Short Name',
      type: 'string',
      group: 'advanced',
      hidden: ({ document }) => !document?.enablePwa,
    }),
    defineField({
      name: 'pwaThemeColor',
      title: 'PWA Theme Color',
      type: 'string',
      group: 'advanced',
      hidden: ({ document }) => !document?.enablePwa,
    }),
    defineField({
      name: 'pwaBackgroundColor',
      title: 'PWA Background Color',
      type: 'string',
      group: 'advanced',
      hidden: ({ document }) => !document?.enablePwa,
    }),
  ],
  preview: {
    prepare() {
      return { title: 'Site Settings' }
    },
  },
})
