/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type VariantGuideline = {
  _type: "variantGuideline";
  variant: string;
  colorToken?: string;
  usageNote?: string;
};

export type ColorToken = {
  _type: "colorToken";
  name: string;
  cssVariable?: string;
  oklch?: string;
  hex?: string;
  rgb?: string;
};

export type ColorPalette = {
  _type: "colorPalette";
  paletteName: string;
  tokens?: Array<
    {
      _key: string;
    } & ColorToken
  >;
};

export type FooterColumn = {
  _type: "footerColumn";
  title: string;
  links?: Array<
    {
      _key: string;
    } & FooterLink
  >;
};

export type FooterLink = {
  _type: "footerLink";
  label: string;
  linkType: "internal" | "external";
  url?: string;
  externalUrl?: string;
  openInNewTab?: boolean;
};

export type DisputeResolutionScheme = {
  _type: "disputeResolutionScheme";
  schemeName: string;
  schemeUrl?: string;
  memberNumber?: string;
  description?: string;
};

export type AnnouncementBar = {
  _type: "announcementBar";
  enabled?: boolean;
  message?: string;
  linkText?: string;
  linkUrl?: string;
  style?: "info" | "warning" | "success" | "emergency";
  dismissible?: boolean;
  showOnPages?: "all" | "homepage-only";
  startDate?: string;
  endDate?: string;
};

export type DayHours = {
  _type: "dayHours";
  day:
    | "Monday"
    | "Tuesday"
    | "Wednesday"
    | "Thursday"
    | "Friday"
    | "Saturday"
    | "Sunday"
    | "Public Holidays";
  openTime?: string;
  closeTime?: string;
  isClosed?: boolean;
};

export type Address = {
  _type: "address";
  street: string;
  suburb?: string;
  city: string;
  postcode?: string;
  region?: string;
  country?: string;
};

export type SocialLink = {
  _type: "socialLink";
  platform:
    | "facebook"
    | "instagram"
    | "linkedin"
    | "youtube"
    | "tiktok"
    | "twitter"
    | "threads";
  url: string;
  label?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type MainNavItem = {
  _type: "mainNavItem";
  label: string;
  url: string;
  megaMenu?: Array<
    {
      _key: string;
    } & NavGroup
  >;
  featuredPosition?: "left" | "right";
};

export type NavGroup = {
  _type: "navGroup";
  title: string;
  isFeatured?: boolean;
  items?: Array<
    {
      _key: string;
    } & Link
  >;
};

export type Link = {
  _type: "link";
  label: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  linkType: "internal" | "external";
  url?: string;
  externalUrl?: string;
  openInNewTab?: boolean;
};

export type DesignSystemUser = {
  _id: string;
  _type: "designSystemUser";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  email: string;
  hashedPin?: string;
  displayName?: string;
  lastLoginAt?: string;
  createdAt?: string;
};

export type ComponentConfig = {
  _id: string;
  _type: "componentConfig";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  componentName: string;
  displayName: string;
  category?: "actions" | "forms" | "layout" | "overlay" | "navigation" | "data";
  approvedVariants?: Array<string>;
  disabledVariants?: Array<string>;
  approvedSizes?: Array<string>;
  defaultVariant?: string;
  defaultSize?: string;
  variantGuidelines?: Array<
    {
      _key: string;
    } & VariantGuideline
  >;
  componentSpecificConfig?: {
    defaultLabel?: string;
    defaultDisabled?: boolean;
    defaultType?: "single" | "multiple";
    defaultCollapsible?: boolean;
    defaultSide?: "top" | "right" | "bottom" | "left";
    defaultOrientation?: "horizontal" | "vertical";
    defaultListVariant?: "default" | "line";
    showCloseButton?: boolean;
    defaultViewport?: boolean;
    defaultPlaceholder?: string;
    defaultMin?: number;
    defaultMax?: number;
    defaultStep?: number;
  };
  previewConfig?: {
    selectedVariant?: string;
    selectedSize?: string;
    previewLabel?: string;
    previewDisabled?: boolean;
  };
};

export type DesignTokens = {
  _id: string;
  _type: "designTokens";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  lastSyncedAt?: string;
  palettes?: Array<
    {
      _key: string;
    } & ColorPalette
  >;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName: string;
  siteTagline?: string;
  siteDescription: string;
  siteUrl: string;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  logoAlt: string;
  logoDark?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  favicon?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  appleTouchIcon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  locale?: "en-NZ" | "mi-NZ";
  currency?: string;
  dateFormat?: "DD/MM/YYYY" | "MM/DD/YYYY" | "YYYY-MM-DD";
  timezone?: string;
  defaultSeoTitle?: string;
  titleTemplate?: string;
  defaultSeoDescription?: string;
  defaultOgImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  twitterHandle?: string;
  twitterCardType?: "summary" | "summary_large_image";
  googleSiteVerification?: string;
  bingSiteVerification?: string;
  noIndexSite?: boolean;
  robotsTxtOverride?: string;
  enableJsonLd?: boolean;
  socialLinks?: Array<
    {
      _key: string;
    } & SocialLink
  >;
  primaryPhone: string;
  tollFreePhone?: string;
  primaryEmail: string;
  headOfficeAddress?: Address;
  googleMapsUrl?: string;
  postalAddress?: Address;
  businessHours?: Array<
    {
      _key: string;
    } & DayHours
  >;
  holidayNotice?: string;
  announcementBar?: AnnouncementBar;
  enableAnalytics?: boolean;
  googleAnalyticsId?: string;
  googleTagManagerId?: string;
  hotjarId?: string;
  metaPixelId?: string;
  linkedinPartnerId?: string;
  customHeadScripts?: string;
  customBodyScripts?: string;
  registeredName: string;
  nzbn?: string;
  fspNumber: string;
  disputeResolutionScheme?: DisputeResolutionScheme;
  regulatoryBody?: string;
  copyrightNotice: string;
  privacyPolicyUrl?: string;
  termsUrl?: string;
  disclosureStatementUrl?: string;
  complaintsUrl?: string;
  accessibilityStatementUrl?: string;
  cookieConsentEnabled?: boolean;
  cookieConsentMessage?: string;
  enableDarkMode?: boolean;
  headerStyle?: "transparent" | "solid" | "sticky";
  footerStyle?: "standard" | "minimal" | "expanded";
  customCss?: string;
  fontPrimary?: string;
  fontSecondary?: string;
  maintenanceMode?: boolean;
  maintenanceMessage?: string;
  maintenanceAllowedIPs?: Array<string>;
  custom404Title?: string;
  custom404Description?: string;
  custom500Title?: string;
  custom500Description?: string;
  enablePwa?: boolean;
  pwaShortName?: string;
  pwaThemeColor?: string;
  pwaBackgroundColor?: string;
};

export type FooterNavigation = {
  _id: string;
  _type: "footerNavigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  headline: string;
  headlineFontSize?: string;
  subheadline?: string;
  columns?: Array<
    {
      _key: string;
    } & FooterColumn
  >;
  newsletterCta?: {
    heading?: string;
    description?: string;
    placeholder?: string;
    buttonLabel?: string;
    disclaimer?: string;
  };
  appStoreLinks?: {
    iosUrl?: string;
    androidUrl?: string;
  };
  showSocialLinks?: boolean;
  showContactInfo?: boolean;
  legalLinks?: Array<
    {
      _key: string;
    } & FooterLink
  >;
};

export type HeaderNavigation = {
  _id: string;
  _type: "headerNavigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  mainNav?: Array<
    {
      _key: string;
    } & MainNavItem
  >;
  utilityNav?: {
    primaryAction?: {
      label: string;
      url: string;
    };
    secondaryAction?: {
      label: string;
      url?: string;
    };
    showSearch?: boolean;
  };
};

export type SanityAssistInstructionTask = {
  _type: "sanity.assist.instructionTask";
  path?: string;
  instructionKey?: string;
  started?: string;
  updated?: string;
  info?: string;
};

export type SanityAssistTaskStatus = {
  _type: "sanity.assist.task.status";
  tasks?: Array<
    {
      _key: string;
    } & SanityAssistInstructionTask
  >;
};

export type SanityAssistSchemaTypeAnnotations = {
  _type: "sanity.assist.schemaType.annotations";
  title?: string;
  fields?: Array<
    {
      _key: string;
    } & SanityAssistSchemaTypeField
  >;
};

export type SanityAssistOutputType = {
  _type: "sanity.assist.output.type";
  type?: string;
};

export type SanityAssistOutputField = {
  _type: "sanity.assist.output.field";
  path?: string;
};

export type AssistInstructionContextReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "assist.instruction.context";
};

export type SanityAssistInstructionContext = {
  _type: "sanity.assist.instruction.context";
  reference: AssistInstructionContextReference;
};

export type AssistInstructionContext = {
  _id: string;
  _type: "assist.instruction.context";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  context?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityAssistInstructionUserInput = {
  _type: "sanity.assist.instruction.userInput";
  message: string;
  description?: string;
};

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }
    | ({
        _key: string;
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string;
      } & SanityAssistInstructionContext)
    | ({
        _key: string;
      } & SanityAssistInstructionUserInput)
  >;
  style?: "normal";
  listItem?: never;
  markDefs?: null;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SanityAssistInstructionFieldRef = {
  _type: "sanity.assist.instruction.fieldRef";
  path?: string;
};

export type SanityAssistInstruction = {
  _type: "sanity.assist.instruction";
  prompt?: SanityAssistInstructionPrompt;
  icon?: string;
  title?: string;
  userId?: string;
  createdById?: string;
  output?: Array<
    | ({
        _key: string;
      } & SanityAssistOutputField)
    | ({
        _key: string;
      } & SanityAssistOutputType)
  >;
};

export type SanityAssistSchemaTypeField = {
  _type: "sanity.assist.schemaType.field";
  path?: string;
  instructions?: Array<
    {
      _key: string;
    } & SanityAssistInstruction
  >;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | VariantGuideline
  | ColorToken
  | ColorPalette
  | FooterColumn
  | FooterLink
  | DisputeResolutionScheme
  | AnnouncementBar
  | DayHours
  | Address
  | SocialLink
  | SanityImageAssetReference
  | Seo
  | SanityImageCrop
  | SanityImageHotspot
  | MainNavItem
  | NavGroup
  | Link
  | DesignSystemUser
  | ComponentConfig
  | DesignTokens
  | SanityFileAssetReference
  | SiteSettings
  | FooterNavigation
  | HeaderNavigation
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | AssistInstructionContextReference
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: src/sanity/lib/queries.ts
// Variable: DESIGN_TOKENS_QUERY
// Query: *[_id == "designTokens"][0] {    lastSyncedAt,    palettes[] {      _key,      paletteName,      tokens[] {        _key,        name,        cssVariable,        oklch,        hex,        rgb      }    }  }
export type DESIGN_TOKENS_QUERY_RESULT =
  | {
      lastSyncedAt: null;
      palettes: null;
    }
  | {
      lastSyncedAt: string | null;
      palettes: Array<{
        _key: string;
        paletteName: string;
        tokens: Array<{
          _key: string;
          name: string;
          cssVariable: string | null;
          oklch: string | null;
          hex: string | null;
          rgb: string | null;
        }> | null;
      }> | null;
    }
  | null;

// Source: src/sanity/lib/queries.ts
// Variable: ALL_COMPONENT_CONFIGS_QUERY
// Query: *[_type == "componentConfig"] | order(displayName asc) {    _id,    componentName,    displayName,    category,    approvedVariants,    disabledVariants,    approvedSizes,    defaultVariant,    defaultSize,    variantGuidelines[] {      _key,      variant,      colorToken,      usageNote    },    componentSpecificConfig,    previewConfig  }
export type ALL_COMPONENT_CONFIGS_QUERY_RESULT = Array<{
  _id: string;
  componentName: string;
  displayName: string;
  category:
    | "actions"
    | "data"
    | "forms"
    | "layout"
    | "navigation"
    | "overlay"
    | null;
  approvedVariants: Array<string> | null;
  disabledVariants: Array<string> | null;
  approvedSizes: Array<string> | null;
  defaultVariant: string | null;
  defaultSize: string | null;
  variantGuidelines: Array<{
    _key: string;
    variant: string;
    colorToken: string | null;
    usageNote: string | null;
  }> | null;
  componentSpecificConfig: {
    defaultLabel?: string;
    defaultDisabled?: boolean;
    defaultType?: "multiple" | "single";
    defaultCollapsible?: boolean;
    defaultSide?: "bottom" | "left" | "right" | "top";
    defaultOrientation?: "horizontal" | "vertical";
    defaultListVariant?: "default" | "line";
    showCloseButton?: boolean;
    defaultViewport?: boolean;
    defaultPlaceholder?: string;
    defaultMin?: number;
    defaultMax?: number;
    defaultStep?: number;
  } | null;
  previewConfig: {
    selectedVariant?: string;
    selectedSize?: string;
    previewLabel?: string;
    previewDisabled?: boolean;
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: COMPONENT_CONFIG_QUERY
// Query: *[_type == "componentConfig" && componentName == $componentName][0] {    _id,    componentName,    displayName,    category,    approvedVariants,    disabledVariants,    approvedSizes,    defaultVariant,    defaultSize,    variantGuidelines[] {      _key,      variant,      colorToken,      usageNote    },    componentSpecificConfig,    previewConfig  }
export type COMPONENT_CONFIG_QUERY_RESULT = {
  _id: string;
  componentName: string;
  displayName: string;
  category:
    | "actions"
    | "data"
    | "forms"
    | "layout"
    | "navigation"
    | "overlay"
    | null;
  approvedVariants: Array<string> | null;
  disabledVariants: Array<string> | null;
  approvedSizes: Array<string> | null;
  defaultVariant: string | null;
  defaultSize: string | null;
  variantGuidelines: Array<{
    _key: string;
    variant: string;
    colorToken: string | null;
    usageNote: string | null;
  }> | null;
  componentSpecificConfig: {
    defaultLabel?: string;
    defaultDisabled?: boolean;
    defaultType?: "multiple" | "single";
    defaultCollapsible?: boolean;
    defaultSide?: "bottom" | "left" | "right" | "top";
    defaultOrientation?: "horizontal" | "vertical";
    defaultListVariant?: "default" | "line";
    showCloseButton?: boolean;
    defaultViewport?: boolean;
    defaultPlaceholder?: string;
    defaultMin?: number;
    defaultMax?: number;
    defaultStep?: number;
  } | null;
  previewConfig: {
    selectedVariant?: string;
    selectedSize?: string;
    previewLabel?: string;
    previewDisabled?: boolean;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: HEADER_NAVIGATION_QUERY
// Query: *[_id == "headerNavigation"][0] {    mainNav[] {      _key,      label,      url,      featuredPosition,      megaMenu[] {        _key,        title,        isFeatured,        items[] {          _key,          label,          description,          image {            asset-> {              _id,              url,              metadata {                lqip,                dimensions { width, height }              }            },            hotspot,            crop,            alt          },          linkType,          url,          externalUrl,          openInNewTab        }      }    },    utilityNav {      primaryAction {        label,        url      },      secondaryAction {        label,        url      },      showSearch    }  }
export type HEADER_NAVIGATION_QUERY_RESULT =
  | {
      mainNav: null;
      utilityNav: null;
    }
  | {
      mainNav: Array<{
        _key: string;
        label: string;
        url: string;
        featuredPosition: "left" | "right" | null;
        megaMenu: Array<{
          _key: string;
          title: string;
          isFeatured: boolean | null;
          items: Array<{
            _key: string;
            label: string;
            description: string | null;
            image: {
              asset: {
                _id: string;
                url: string;
                metadata: {
                  lqip: string | null;
                  dimensions: {
                    width: number;
                    height: number;
                  } | null;
                } | null;
              } | null;
              hotspot: SanityImageHotspot | null;
              crop: SanityImageCrop | null;
              alt: null;
            } | null;
            linkType: "external" | "internal";
            url: string | null;
            externalUrl: string | null;
            openInNewTab: boolean | null;
          }> | null;
        }> | null;
      }> | null;
      utilityNav: {
        primaryAction: {
          label: string;
          url: string;
        } | null;
        secondaryAction: {
          label: string;
          url: string | null;
        } | null;
        showSearch: boolean | null;
      } | null;
    }
  | null;

// Source: src/sanity/lib/queries.ts
// Variable: FOOTER_NAVIGATION_QUERY
// Query: *[_id == "footerNavigation"][0] {    headline,    headlineFontSize,    subheadline,    columns[] {      _key,      title,      links[] {        _key,        label,        linkType,        url,        externalUrl,        openInNewTab      }    },    newsletterCta {      heading,      description,      placeholder,      buttonLabel,      disclaimer    },    appStoreLinks {      iosUrl,      androidUrl    },    showSocialLinks,    showContactInfo,    legalLinks[] {      _key,      label,      linkType,      url,      externalUrl,      openInNewTab    }  }
export type FOOTER_NAVIGATION_QUERY_RESULT =
  | {
      headline: null;
      headlineFontSize: null;
      subheadline: null;
      columns: null;
      newsletterCta: null;
      appStoreLinks: null;
      showSocialLinks: null;
      showContactInfo: null;
      legalLinks: null;
    }
  | {
      headline: string;
      headlineFontSize: string | null;
      subheadline: string | null;
      columns: Array<{
        _key: string;
        title: string;
        links: Array<{
          _key: string;
          label: string;
          linkType: "external" | "internal";
          url: string | null;
          externalUrl: string | null;
          openInNewTab: boolean | null;
        }> | null;
      }> | null;
      newsletterCta: {
        heading: string | null;
        description: string | null;
        placeholder: string | null;
        buttonLabel: string | null;
        disclaimer: string | null;
      } | null;
      appStoreLinks: {
        iosUrl: string | null;
        androidUrl: string | null;
      } | null;
      showSocialLinks: boolean | null;
      showContactInfo: boolean | null;
      legalLinks: Array<{
        _key: string;
        label: string;
        linkType: "external" | "internal";
        url: string | null;
        externalUrl: string | null;
        openInNewTab: boolean | null;
      }> | null;
    }
  | null;

// Source: src/sanity/lib/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_id == "siteSettings"][0] {    siteName,    siteTagline,    siteDescription,    siteUrl,    logo,    logoAlt,    titleTemplate,    defaultSeoTitle,    defaultSeoDescription,    defaultOgImage,    twitterHandle,    twitterCardType,    googleSiteVerification,    bingSiteVerification,    noIndexSite,    enableJsonLd,    enableAnalytics,    googleAnalyticsId,    googleTagManagerId,    socialLinks[] { _key, platform, url, label },    primaryPhone,    tollFreePhone,    primaryEmail,    headOfficeAddress,    googleMapsUrl,    postalAddress,    businessHours[] { _key, day, openTime, closeTime, isClosed },    holidayNotice,    announcementBar,    registeredName,    nzbn,    fspNumber,    copyrightNotice,    disputeResolutionScheme,    regulatoryBody,    privacyPolicyUrl,    termsUrl,    disclosureStatementUrl,    complaintsUrl,    accessibilityStatementUrl,    cookieConsentEnabled,    cookieConsentMessage,    locale,    maintenanceMode,    maintenanceMessage,    headerStyle,    footerStyle  }
export type SITE_SETTINGS_QUERY_RESULT =
  | {
      siteName: null;
      siteTagline: null;
      siteDescription: null;
      siteUrl: null;
      logo: null;
      logoAlt: null;
      titleTemplate: null;
      defaultSeoTitle: null;
      defaultSeoDescription: null;
      defaultOgImage: null;
      twitterHandle: null;
      twitterCardType: null;
      googleSiteVerification: null;
      bingSiteVerification: null;
      noIndexSite: null;
      enableJsonLd: null;
      enableAnalytics: null;
      googleAnalyticsId: null;
      googleTagManagerId: null;
      socialLinks: null;
      primaryPhone: null;
      tollFreePhone: null;
      primaryEmail: null;
      headOfficeAddress: null;
      googleMapsUrl: null;
      postalAddress: null;
      businessHours: null;
      holidayNotice: null;
      announcementBar: null;
      registeredName: null;
      nzbn: null;
      fspNumber: null;
      copyrightNotice: null;
      disputeResolutionScheme: null;
      regulatoryBody: null;
      privacyPolicyUrl: null;
      termsUrl: null;
      disclosureStatementUrl: null;
      complaintsUrl: null;
      accessibilityStatementUrl: null;
      cookieConsentEnabled: null;
      cookieConsentMessage: null;
      locale: null;
      maintenanceMode: null;
      maintenanceMessage: null;
      headerStyle: null;
      footerStyle: null;
    }
  | {
      siteName: string;
      siteTagline: string | null;
      siteDescription: string;
      siteUrl: string;
      logo: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      };
      logoAlt: string;
      titleTemplate: string | null;
      defaultSeoTitle: string | null;
      defaultSeoDescription: string | null;
      defaultOgImage: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      twitterHandle: string | null;
      twitterCardType: "summary_large_image" | "summary" | null;
      googleSiteVerification: string | null;
      bingSiteVerification: string | null;
      noIndexSite: boolean | null;
      enableJsonLd: boolean | null;
      enableAnalytics: boolean | null;
      googleAnalyticsId: string | null;
      googleTagManagerId: string | null;
      socialLinks: Array<{
        _key: string;
        platform:
          | "facebook"
          | "instagram"
          | "linkedin"
          | "threads"
          | "tiktok"
          | "twitter"
          | "youtube";
        url: string;
        label: string | null;
      }> | null;
      primaryPhone: string;
      tollFreePhone: string | null;
      primaryEmail: string;
      headOfficeAddress: Address | null;
      googleMapsUrl: string | null;
      postalAddress: Address | null;
      businessHours: Array<{
        _key: string;
        day:
          | "Friday"
          | "Monday"
          | "Public Holidays"
          | "Saturday"
          | "Sunday"
          | "Thursday"
          | "Tuesday"
          | "Wednesday";
        openTime: string | null;
        closeTime: string | null;
        isClosed: boolean | null;
      }> | null;
      holidayNotice: string | null;
      announcementBar: AnnouncementBar | null;
      registeredName: string;
      nzbn: string | null;
      fspNumber: string;
      copyrightNotice: string;
      disputeResolutionScheme: DisputeResolutionScheme | null;
      regulatoryBody: string | null;
      privacyPolicyUrl: string | null;
      termsUrl: string | null;
      disclosureStatementUrl: string | null;
      complaintsUrl: string | null;
      accessibilityStatementUrl: string | null;
      cookieConsentEnabled: boolean | null;
      cookieConsentMessage: string | null;
      locale: "en-NZ" | "mi-NZ" | null;
      maintenanceMode: boolean | null;
      maintenanceMessage: string | null;
      headerStyle: "solid" | "sticky" | "transparent" | null;
      footerStyle: "expanded" | "minimal" | "standard" | null;
    }
  | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_id == "designTokens"][0] {\n    lastSyncedAt,\n    palettes[] {\n      _key,\n      paletteName,\n      tokens[] {\n        _key,\n        name,\n        cssVariable,\n        oklch,\n        hex,\n        rgb\n      }\n    }\n  }\n': DESIGN_TOKENS_QUERY_RESULT;
    '\n  *[_type == "componentConfig"] | order(displayName asc) {\n    _id,\n    componentName,\n    displayName,\n    category,\n    approvedVariants,\n    disabledVariants,\n    approvedSizes,\n    defaultVariant,\n    defaultSize,\n    variantGuidelines[] {\n      _key,\n      variant,\n      colorToken,\n      usageNote\n    },\n    componentSpecificConfig,\n    previewConfig\n  }\n': ALL_COMPONENT_CONFIGS_QUERY_RESULT;
    '\n  *[_type == "componentConfig" && componentName == $componentName][0] {\n    _id,\n    componentName,\n    displayName,\n    category,\n    approvedVariants,\n    disabledVariants,\n    approvedSizes,\n    defaultVariant,\n    defaultSize,\n    variantGuidelines[] {\n      _key,\n      variant,\n      colorToken,\n      usageNote\n    },\n    componentSpecificConfig,\n    previewConfig\n  }\n': COMPONENT_CONFIG_QUERY_RESULT;
    '\n  *[_id == "headerNavigation"][0] {\n    mainNav[] {\n      _key,\n      label,\n      url,\n      featuredPosition,\n      megaMenu[] {\n        _key,\n        title,\n        isFeatured,\n        items[] {\n          _key,\n          label,\n          description,\n          image {\n            asset-> {\n              _id,\n              url,\n              metadata {\n                lqip,\n                dimensions { width, height }\n              }\n            },\n            hotspot,\n            crop,\n            alt\n          },\n          linkType,\n          url,\n          externalUrl,\n          openInNewTab\n        }\n      }\n    },\n    utilityNav {\n      primaryAction {\n        label,\n        url\n      },\n      secondaryAction {\n        label,\n        url\n      },\n      showSearch\n    }\n  }\n': HEADER_NAVIGATION_QUERY_RESULT;
    '\n  *[_id == "footerNavigation"][0] {\n    headline,\n    headlineFontSize,\n    subheadline,\n    columns[] {\n      _key,\n      title,\n      links[] {\n        _key,\n        label,\n        linkType,\n        url,\n        externalUrl,\n        openInNewTab\n      }\n    },\n    newsletterCta {\n      heading,\n      description,\n      placeholder,\n      buttonLabel,\n      disclaimer\n    },\n    appStoreLinks {\n      iosUrl,\n      androidUrl\n    },\n    showSocialLinks,\n    showContactInfo,\n    legalLinks[] {\n      _key,\n      label,\n      linkType,\n      url,\n      externalUrl,\n      openInNewTab\n    }\n  }\n': FOOTER_NAVIGATION_QUERY_RESULT;
    '\n  *[_id == "siteSettings"][0] {\n    siteName,\n    siteTagline,\n    siteDescription,\n    siteUrl,\n    logo,\n    logoAlt,\n    titleTemplate,\n    defaultSeoTitle,\n    defaultSeoDescription,\n    defaultOgImage,\n    twitterHandle,\n    twitterCardType,\n    googleSiteVerification,\n    bingSiteVerification,\n    noIndexSite,\n    enableJsonLd,\n    enableAnalytics,\n    googleAnalyticsId,\n    googleTagManagerId,\n    socialLinks[] { _key, platform, url, label },\n    primaryPhone,\n    tollFreePhone,\n    primaryEmail,\n    headOfficeAddress,\n    googleMapsUrl,\n    postalAddress,\n    businessHours[] { _key, day, openTime, closeTime, isClosed },\n    holidayNotice,\n    announcementBar,\n    registeredName,\n    nzbn,\n    fspNumber,\n    copyrightNotice,\n    disputeResolutionScheme,\n    regulatoryBody,\n    privacyPolicyUrl,\n    termsUrl,\n    disclosureStatementUrl,\n    complaintsUrl,\n    accessibilityStatementUrl,\n    cookieConsentEnabled,\n    cookieConsentMessage,\n    locale,\n    maintenanceMode,\n    maintenanceMessage,\n    headerStyle,\n    footerStyle\n  }\n': SITE_SETTINGS_QUERY_RESULT;
  }
}
