/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: src/sanity/extract.json
export type MainNavItem = {
  _type: "mainNavItem";
  label: string;
  url: string;
  megaMenu?: Array<
    {
      _key: string;
    } & NavGroup
  >;
};

export type NavGroup = {
  _type: "navGroup";
  title: string;
  items?: Array<
    {
      _key: string;
    } & Link
  >;
};

export type Link = {
  _type: "link";
  label: string;
  linkType: "internal" | "external";
  url?: string;
  externalUrl?: string;
  openInNewTab?: boolean;
};

export type HeaderNavigation = {
  _id: string;
  _type: "headerNavigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  mainNav?: Array<
    {
      _key: string;
    } & MainNavItem
  >;
  utilityNav?: {
    primaryAction?: {
      label: string;
      url: string;
    };
    secondaryAction?: {
      label: string;
      url?: string;
    };
    showSearch?: boolean;
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | MainNavItem
  | NavGroup
  | Link
  | HeaderNavigation
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/lib/queries.ts
// Variable: HEADER_NAVIGATION_QUERY
// Query: *[_id == "headerNavigation"][0] {    mainNav[] {      _key,      label,      url,      megaMenu[] {        _key,        title,        items[] {          _key,          label,          linkType,          url,          externalUrl,          openInNewTab        }      }    },    utilityNav {      primaryAction {        label,        url      },      secondaryAction {        label,        url      },      showSearch    }  }
export type HEADER_NAVIGATION_QUERY_RESULT =
  | {
      mainNav: null;
      utilityNav: null;
    }
  | {
      mainNav: Array<{
        _key: string;
        label: string;
        url: string;
        megaMenu: Array<{
          _key: string;
          title: string;
          items: Array<{
            _key: string;
            label: string;
            linkType: "external" | "internal";
            url: string | null;
            externalUrl: string | null;
            openInNewTab: boolean | null;
          }> | null;
        }> | null;
      }> | null;
      utilityNav: {
        primaryAction: {
          label: string;
          url: string;
        } | null;
        secondaryAction: {
          label: string;
          url: string | null;
        } | null;
        showSearch: boolean | null;
      } | null;
    }
  | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_id == "headerNavigation"][0] {\n    mainNav[] {\n      _key,\n      label,\n      url,\n      megaMenu[] {\n        _key,\n        title,\n        items[] {\n          _key,\n          label,\n          linkType,\n          url,\n          externalUrl,\n          openInNewTab\n        }\n      }\n    },\n    utilityNav {\n      primaryAction {\n        label,\n        url\n      },\n      secondaryAction {\n        label,\n        url\n      },\n      showSearch\n    }\n  }\n': HEADER_NAVIGATION_QUERY_RESULT;
  }
}
